#!/bin/bash
set -e
if [ "$(whoami)" == "root" ];then
  exec sudo -u "virtkick-run" "$0" "$@"
fi

BASE_DIR="$(readlink -f "$(dirname "$0")")"
cd "$BASE_DIR"

XDG_RUNTIME_DIR= setup/test_libvirt.py || (echo "libvirt or libvirt-python are not working, make sure libvirtd is running and proper python bindings are installed" && exit 1)

. setup/run_env.sh
exec node src/virtkick.js

